### ISSUE TITLE
Plotting multiple deltas in one plot

### ISSUE THREAD

**Issue by weedcentipede** [jmonlong/Hippocamplus#5]
Hi, 
Saw your repo, it's amazing, 
I was wondering if you've tried to plot multiple deltas into a single plot (Using same reference for example)

Thanks!, 
Luis Alfonso.

**Comment by jmonlong** [comment]
Hi Luis Alfonso,

Glad it's useful for someone else. I haven't tried plotting several delta files but I would imagine it's just a question of importing each one separately and *rbind*ing the data.frames that comes out of the *readDelta* function. The contigs are grouped by *rid*/*qid* in the graphs already so they should be fine with information from multiple delta files.

Cheers,
Jean

**Comment by weedcentipede** [comment]
Hey Jean, 
Thank you!, 

I'll try and let you know,
Cheers, 
Luis Alfonso.
